# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_login', '0001_initial'),
        ('matt_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='added_quotes',
        ),
        migrations.AddField(
            model_name='quotes',
            name='fav_quotes',
            field=models.ManyToManyField(related_name='fav_quotes', to='new_login.User'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='quoted_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotes',
            name='quote',
            field=models.CharField(max_length=255),
        ),
    ]
